### ISSUE TITLE
Hangs on say

### ISSUE THREAD

**Issue by rkumar** [vitorpamplona/shtweet#2]
I am able to login, and see(). but say() hangs.
Am on MAC OSX, zsh.

I've put debug statements, and found that the get auth code produces a huge output
        auth=`curl -s $COOKIE_LINE http://mobile.twitter.com`

Execution then hangs on the following line:
     auth=`echo $auth | sed -n -e "s/.*<form action .....

**Comment by vitorpamplona** [comment]
Hum... I could not use _sed_ in mac at all. It hangs all the time. It seems that it is a different version than the Linux one.

**Comment by rkumar** [comment]
Ok, I replace _sed_ with **gsed**. Now it goes through but gives me a "redirected" message and then "Done".

But nothing shows up on twitter.

You are being redirected. (removed html code)
Done

(I pressed Comment and Close accidentally)

**Comment by vitorpamplona** [comment]
Hum... I will spend some time this weekend to replace sed with perl. It seems that sed has a lot of variations and that is bad. You may also try it. I think it will work better than sed.

**Comment by rkumar** [comment]
perl would be nice. I love sed for quick stuff, but it bites me for serious stuff since the sed delimiter can often be in the data itself. 

Essentially, linux uses GNU commands (e.g. coreutils), Mac uses BSD and there is a big variation in their arguments (e.g. date command). When we install coreutils on OSX by default it prepends a "g" to the files. So we get gdate, gsed, gsleep etc. We can override this by using "use_default_names" but then i never know how someone else may have installed coreutils.

This drove me to rewriting everything in ruby.

**Comment by pjv** [comment]
running on ubuntu natty, i get the same issue that rkumar reported above. on trying "say" i get an html response saying that i am being redirected to mobile.twitter.com and then "Done" and then no tweet shows up.

**Comment by vitorpamplona** [comment]
Hey guys, 

I just changed SED to PERL. Can you pull it and try again? 

Thanks.

**Comment by pjv** [comment]
working for me now on both OS X and ubuntu natty.

**Comment by vitorpamplona** [comment]
Awesome! Thanks a lot!

**Comment by rkumar** [comment]
A note for OSX users:

Working fine with me now too, although the _curl_ version can be an issue. "say" was not working with the macport installed curl, but when i used the recent Lion installed curl in /usr/bin it worked.
Thanks.
